version: '3'

tasks:
  db-rev:
    desc: create a database migration, pass a string as commit string
    cmds:
      - docker compose exec api sh -c "alembic -c /opt/labs/alembic.ini revision --autogenerate -m {{.CLI_ARGS}}"
  db-migrate:
    desc: migrates models to HEAD
    cmds:
      - docker compose exec api sh -c "alembic -c /opt/labs/alembic.ini upgrade head"
