[api]
enabled = true
address = "0.0.0.0:8686"
playground = false

[sources.logs]
type = "file"
ignore_older_secs = 600
include = ["/var/log/postgresql/*.log"]
read_from = "beginning"

[sinks.console]
inputs = ["logs"]
target = "stdout"
type = "console"
encoding.codec = "json"
