# Commentary on letsencrypt and how the object store maps

[http]
    [http.middlewares]
        [http.middlewares.host.headers]
            [http.middlewares.host.headers.customRequestHeaders]
                Host = "bucket-name.website-ap-south-1.linodeobjects.com"

    [http.routers]
        [http.routers.website]
            entryPoints = ["https"]
            service = "bucket"
            middlewares = "host"
            rule = "Host(`productiondomain.com`)"
            priority=1
            [http.routers.website.tls]
                certResolver = "letsencrypt"

    [http.services]
        [http.services.bucket.loadBalancer]
            [[http.services.bucket.loadBalancer.servers]]
                url = "http://bucker-name.website-ap-south-1.linodeobjects.com"


[tls.options]
  [tls.options.default]
    maxVersion = "VersionTLS13"

  [tls.options.maxtls12]
    maxVersion = "VersionTLS12"
