[tool.poetry]
name = "labs"
version = "0.1.0"
description = ""
authors = ["Dev Mukherjee <devraj@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pendulum = "^2.1.2"
SQLAlchemy = "^1.4.40"
fastapi = "^0.85.0"
alembic = "^1.8.1"
celery = "^5.2.7"
uvicorn = "^0.18.3"
gunicorn = "^20.1.0"
websockets = "^10.3"
fluent-logger = "^0.10.0"
redis = "^4.3.4"
asyncpg = "^0.26.0"
gevent = "^22.8.0"
email-validator = "^1.2.1"
pyotp = "^2.6.0"
redmail = "^0.4.0"
stripe = "^4.1.0"
clicksend-client = "^5.0.72"
minio = "^7.1.11"
passlib = "^1.7.4"
bcrypt = "^4.0.0"
PyJWT = "^2.5.0"
humps = "^0.2.2"

[tool.poetry.dev-dependencies]
watchdog = "^2.1.8"

[tool.poetry.scripts]
init-db = "labs.db.init_db"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
