[tool.poetry]
name = "labs"
version = "0.1.0"
description = ""
authors = ["Dev Mukherjee <devraj@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pendulum = "^2.1.2"
SQLAlchemy = "^1.4.36"
fastapi = "^0.78.0"
alembic = "^1.7.7"
celery = "^5.2.6"
uvicorn = "^0.17.6"
gunicorn = "^20.1.0"
websockets = "^10.3"
fluent-logger = "^0.10.0"
redis = "^4.3.1"
asyncpg = "^0.25.0"
gevent = "^21.12.0"
email-validator = "^1.2.1"
pyotp = "^2.6.0"
redmail = "^0.4.0"
stripe = "^3.5.0"
fastapi-jwt-auth = "^0.5.0"
clicksend-client = "^5.0.72"
minio = "^7.1.10"
passlib = "^1.7.4"
bcrypt = "^3.2.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
watchdog = "^2.1.8"

[tool.poetry.scripts]
init-db = "labs.db.init_db"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
