[tool.poetry]
name = "labs"
version = "0.1.0"
description = "A template for building Python based web applications"
authors = [
    "Dev Mukherjee <devraj@gmail.com>"
]
repository = "https://github.com/anomaly/lab-python-server"
documentation = "https://anomaly.academy"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pendulum = "^2.1.2"
SQLAlchemy = "^2.0.9"
fastapi = "^0.95.1"
alembic = "^1.10.3"
celery = "^5.2.7"
uvicorn = "^0.21.1"
gunicorn = "^20.1.0"
websockets = "^10.4"
redis = "^4.5.4"
asyncpg = "^0.27.0"
gevent = "^22.10.1"
email-validator = "^2.0.0.post1"
pyotp = "^2.8.0"
redmail = "^0.6.0"
stripe = "^5.4.0"
clicksend-client = "^5.0.72"
minio = "^7.1.14"
bcrypt = "^4.0.1"
PyJWT = "^2.6.0"
pyhumps = "^3.8.0"
python-multipart = "^0.0.5"
pytest = "^7.3.1"
pytz = "^2023.3"
httpx = "^0.24.0"

[tool.poetry.dev-dependencies]
watchdog = "^2.1.8"

[tool.poetry.scripts]
initdb = "labs.db:initalise"

[tool.poetry.group.dev.dependencies]
pytest = "^7.1.3"
pytest-order = "^1.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
